services:
  tidescraper.api:
    image: tidescraper.api
    build:
      context: .
      dockerfile: TideScraper.Api/Dockerfile
    environment:
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
    ports:
      - "8080:8080"
  
  redis:
    image: redis:alpine
    container_name: my-redis
    ports:
      - "6379:6379"